frontend/package-lock.json
frontend/package.json
frontend/src/components/ShareButton.tsx

fix: share functionality on Safari

---

frontend/src/App.tsx

feat: do not display Files if it is empty

---

app.json
backend/package-lock.json
backend/package.json
backend/src/index.ts
backend/src/utils.ts
frontend/src/App.tsx
frontend/src/components/ResponseFile.tsx
frontend/src/constants.ts
frontend/src/utils.ts
types/api.d.ts

feat: added example for playwright-video and refactorement

---

Dockerfile
backend/package-lock.json
backend/package.json
backend/src/index.ts
frontend/package-lock.json
frontend/package.json
frontend/src/App.tsx
frontend/src/index.tsx

Closes #18
Normally I don't like hardcoding API tokens, but for Sentry in the frontend it seems fine because it's nevertheless always public.

feat: enabled Sentry

---

.eslintignore
.eslintrc.js
.github/workflows/nodejs.yml
.gitignore
backend/src/index.ts
backend/src/utils.ts
frontend/package.json
frontend/src/App.tsx
frontend/src/components/Header.tsx
frontend/src/components/ResponseFile.tsx
frontend/src/components/ShareButton.tsx
frontend/src/constants.ts
package-lock.json
package.json
types/api.d.ts

@arjun27 what do you think? I don't like it very much, that we have now three `packages.json` files. Is it better to have linting separated for backend and frontend? Maybe okay for now.
(Prettier would maybe be also quite nice) 
Close #20

feat: added linting

---

backend/src/index.ts
backend/src/utils.ts
frontend/src/App.tsx
frontend/src/components/Header.tsx
frontend/src/components/ResponseFile.tsx
frontend/src/components/ShareButton.tsx
frontend/src/utils.ts

Previously for not existing variables a not meaningful error was shown. With this change the actual exception which was thrown will be displayed.
cc @arjun27

fix: notify for server side errors

---

README.md
app.json
frontend/public/index.html
frontend/src/App.tsx
frontend/src/components/ExampleWrapper.tsx
frontend/src/components/ShareButton.tsx
frontend/src/constants.ts
frontend/src/utils.ts

feat: added descriptions to examples

---

frontend/src/App.tsx
frontend/src/hooks/useDarkMode.ts
frontend/src/index.css
frontend/src/index.tsx

Not sure if I should place a toggle e.g. on the top right. Currently the operating system setting will be used.

feat: dark mode

---

backend/src/playwright.ts
backend/src/utils.ts
frontend/src/App.tsx

feat: keep code on page exit (fix: #39)

---

backend/package-lock.json
backend/package.json
backend/src/utils.ts

Avoid to many parallel opened connections per request.
Closes #40

feat: added rate limiter via bottleneck lib

---

frontend/Caddyfile
frontend/config-overrides.js
frontend/package-lock.json
frontend/package.json

fix: service worker caching issue

---

backend/package-lock.json
backend/src/index.ts
docker-compose.yml
frontend/package-lock.json

In combination with uptimerobot I can be sure that the application will be available as expected.

feat: basic health endpoint

---

backend/src/utils.ts

Applied following hotfix until the new version was released: https://github.com/patriksimek/vm2/issues/268#issuecomment-593536163

fix: RCE attack via vm2

---

frontend/Dockerfile
frontend/src/constants.ts
frontend/src/examples/.eslintrc.json
frontend/src/examples/evaluate-javascript.js
frontend/src/examples/generate-pdf.js
frontend/src/examples/intercept-requests-complex.js
frontend/src/examples/intercept-requests.js
frontend/src/examples/mobile-and-geolocation.js
frontend/src/examples/page-screenshot.js
frontend/src/examples/record-video.js
frontend/src/examples/todo-mvc.js
tests/.qawolf/tests/try-playwright.test.js

feat: reworked examples

---

frontend/src/App.tsx
frontend/src/components/CodeContext.tsx
frontend/src/components/Editor/index.tsx

fix: CTRL + Enter was not working

---

backend/package-lock.json
backend/package.json
frontend/package-lock.json
frontend/package.json
frontend/src/components/Editor/types.txt
frontend/src/utils.ts
package-lock.json
package.json

fix: video example was not working

---

control-service/main.go
e2e/try-playwright.spec.ts
frontend/src/components/Header.module.css
frontend/src/components/Header.tsx
frontend/src/components/ShareButton/index.tsx
frontend/src/examples/record-video.js
frontend/src/hooks/useDarkMode.ts
frontend/src/utils.ts

- get rid of deprecated media query event
- fix responsive header and hide items on mobile view
- wait for network idle on record video example
- add e2e tests for share functionality
- increase snippet length to 7 characters

fix: smaller nits

---

file-service/main.go

feat(file-service): delete files after 1 day

---

control-service/main.go
frontend/src/components/App/index.tsx
frontend/src/components/RightPanel/RightOutputPanel/index.tsx
frontend/src/components/RightPanel/index.tsx
frontend/src/utils.ts
types/api.d.ts
worker/src/index.ts
worker/src/utils.ts

Between worker and control microservice

chore: rework RPC protocol

---

frontend/src/components/App/index.tsx
frontend/src/utils.ts

Should fix the errors if localStorage is not available on mobile devices.

fix: localStorage not available

---

.github/workflows/nodejs.yml
docker-compose.yml
frontend/Caddyfile

devops: push Docker images on GitHub Actions

---

control-service/Dockerfile
file-service/Dockerfile
frontend/src/components/Editor/types.txt
frontend/src/examples/crawl-y-combinator.js
frontend/src/examples/evaluate-javascript.js
frontend/src/examples/generate-pdf.js
frontend/src/examples/intercept-modify-requests.js
frontend/src/examples/intercept-requests.js
frontend/src/examples/mobile-and-geolocation.js
frontend/src/examples/page-screenshot.js
frontend/src/examples/record-video.js
frontend/src/examples/todo-mvc.js
scripts/migration/Dockerfile
update_pw.sh
worker/package-lock.json
worker/package.json
worker/src/playwright.ts
worker/src/utils.ts

- Remove playwright-video we kept it for a few months and now the integrated video support seems stable and the way to go
- Using Go 1.16 for the microservices
- standardise quote styles in examples to single quotes

chore: remove playwright-video and various other cleanups

---

frontend/src/components/Editor/index.tsx

unbind ctrl+L from monaco

---

.github/workflows/nodejs.yml
README.md
control-service/workers.go
frontend/package-lock.json
frontend/package.json
frontend/src/components/Editor/types.txt
k8/control-deployment.yaml
worker/Dockerfile
worker/package-lock.json
worker/package.json

chore: bump minor deps

---

control-service/main.go
file-service/Dockerfile
file-service/main.go
internal/echoutils/echoutils.go

chore: enhance error reporting for echo

---

internal/worker/files.go
internal/worker/worker.go
worker-java/Dockerfile
worker-java/main.go
worker-java/pom.xml

chore: use no network during mvn compile

---

control-service/workers.go

chore: add CPU and memory limits

---

frontend/src/components/CodeContext.tsx
frontend/src/components/Editor/index.tsx
frontend/src/utils.ts

fix: frontend enhancements

---

frontend/src/components/Header.tsx

Fix documentation link in header

---

e2e/package-lock.json
e2e/package.json
e2e/tests/visual.spec.ts

Supersedes https://github.com/mxschmitt/try-playwright/pull/264

test: rewrite some tests to make them more reliable
